
package sendmessage.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SendSMS", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "http://www.webservicex.net/SendSMS.asmx?WSDL")
public class SendSMS
    extends Service
{

    private final static URL SENDSMS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sendmessage.client.SendSMS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sendmessage.client.SendSMS.class.getResource(".");
            url = new URL(baseUrl, "http://www.webservicex.net/SendSMS.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/SendSMS.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SENDSMS_WSDL_LOCATION = url;
    }

    public SendSMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendSMS() {
        super(SENDSMS_WSDL_LOCATION, new QName("http://www.webserviceX.NET", "SendSMS"));
    }

    /**
     * 
     * @return
     *     returns SendSMSSoap
     */
    @WebEndpoint(name = "SendSMSSoap")
    public SendSMSSoap getSendSMSSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET", "SendSMSSoap"), SendSMSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendSMSSoap
     */
    @WebEndpoint(name = "SendSMSSoap")
    public SendSMSSoap getSendSMSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET", "SendSMSSoap"), SendSMSSoap.class, features);
    }

}
